name: Feature request
description: Suggest a change to the application.
body:
  - type: textarea
    id: need
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Suggested behavior
    validations:
      required: true
