const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const file = path.join(__dirname, '..', 'index.html');
let html = fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
const scripts = [...html.matchAll(/<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)];
if (!scripts.length) throw new Error('No inline application script found');
const hashes = scripts.map(([, script]) => "'sha256-" + crypto.createHash('sha256').update(script).digest('base64') + "'");
html = html.replace(/script-src [^;]+;/, "script-src 'self' " + hashes.join(' ') + ';');
fs.writeFileSync(file, html);
console.log('Updated the application script integrity policy.');
